// magi-cp gjc gate shim v1 — session_start lifecycle observer. FROZEN.
// Generated by magi-cp; do not edit — bump shim_version + regen golden on any change.
//
// Contract (design brief §5.3):
//   - Exactly ONE handler registered for exactly "session_start".
//   - Observe-only: fire-and-forget gate invocation; always returns undefined.
//   - Failures here MUST NOT block the session; swallow own errors.
import { spawnSync } from "node:child_process";

const GATE: string = (process.env.MAGI_CP_GATE_BIN as string | undefined) ?? "magi-cp";
const DEADLINE_MS = 10_000;

function safe<T>(fn: () => T): T | undefined {
  try { return fn(); } catch { return undefined; }
}

export default function factory(api: { on: Function; logger: unknown }): void {
  api.on("session_start", (event: any, ctx: any): undefined => {
    try {
      const payload: string = JSON.stringify({
        gjc_event: "session_start",
        tool_name: "",
        tool_call_id: "",
        tool_input: {},
        session_id: safe(() => ctx?.sessionManager?.getSessionId?.()) ?? "",
        session_file: safe(() => ctx?.sessionManager?.getSessionFile?.()) ?? "",
        cwd: String(ctx?.cwd ?? ""),
        model: safe(() => ctx?.model?.id) ?? "",
        shim_version: "1",
      });
      spawnSync(GATE, ["gate", "--runtime", "gjc"], {
        input: payload,
        timeout: DEADLINE_MS,
        encoding: "utf8",
      });
    } catch {
      // Lifecycle observer: swallow errors, never block.
    }
    return undefined;
  });
}
