// magi-cp gjc gate shim v1. FROZEN: zero policy logic.
// Generated by magi-cp; do not edit — bump shim_version + regen golden on any change.
//
// Contract (design brief §5):
//   - Exactly ONE handler registered for exactly "tool_call".
//   - No policy logic: never inspects tool_name/tool_input semantically.
//   - Fail-closed on every shim-local failure (spawn error, timeout, parse).
//   - Self-deadline: spawnSync timeout: 10_000 ms (gjc imposes none).
//   - Silent allow: returns undefined (not {block:false}).
//   - Block: returns {block: true, reason: "..."}.
import { spawnSync } from "node:child_process";

const GATE: string = (process.env.MAGI_CP_GATE_BIN as string | undefined) ?? "magi-cp";
const DEADLINE_MS = 10_000;

function safe<T>(fn: () => T): T | undefined {
  try { return fn(); } catch { return undefined; }
}

export default function factory(api: { on: Function; logger: unknown }): void {
  api.on("tool_call", (event: any, ctx: any): { block: boolean; reason: string } | undefined => {
    const payload: string = JSON.stringify({
      gjc_event: "tool_call",
      tool_name: String(event?.toolName ?? ""),
      tool_call_id: String(event?.toolCallId ?? ""),
      tool_input: (event?.input ?? {}) as Record<string, unknown>,
      session_id: safe(() => ctx?.sessionManager?.getSessionId?.()) ?? "",
      session_file: safe(() => ctx?.sessionManager?.getSessionFile?.()) ?? "",
      cwd: String(ctx?.cwd ?? ""),
      model: safe(() => ctx?.model?.id) ?? "",
      shim_version: "1",
    });
    let res: ReturnType<typeof spawnSync>;
    try {
      res = spawnSync(GATE, ["gate", "--runtime", "gjc"], {
        input: payload,
        timeout: DEADLINE_MS,
        encoding: "utf8",
      });
    } catch (e: unknown) {
      return { block: true, reason: `magi-cp gate error (fail-closed): spawn ${String(e)}` };
    }
    if (res.error !== undefined || res.status === null) {
      return {
        block: true,
        reason: `magi-cp gate error (fail-closed): ${(res.error as Error | undefined)?.message ?? "timeout"}`,
      };
    }
    const out: string = ((res.stdout as string) ?? "").trim();
    if (!out) return undefined; // silent allow
    try {
      const verdict: unknown = JSON.parse(out);
      if (verdict !== null && typeof verdict === "object" && (verdict as any).block === true) {
        return { block: true, reason: String((verdict as any).reason ?? "MAGI: blocked") };
      }
      return undefined; // {"block": false} or any non-blocking response
    } catch {
      return { block: true, reason: "magi-cp gate error (fail-closed): unparseable verdict" };
    }
  });
}
