#!/usr/bin/env bash
# magi-control-plane quickstart installer.
#
# One-liner for alpha users:
#   curl -fsSL https://cloud.openmagi.ai/install.sh | bash -s -- mcp_…
#
# What it does:
#   1) Verify python3.11+ on PATH (install hint if missing)
#   2) pip install --user magi-cp-alpha @ git+https://github.com/openmagi/magi-control-plane
#      (until we publish to PyPI; switches to PyPI when GA)
#   3) Download managed-settings.json + magi-gate.sh from the cloud
#   4) Drop them at ~/.claude/managed-settings.json + ~/.local/bin/magi-gate.sh
#   5) Persist MAGI_CP_API_KEY + MAGI_CP_CLOUD_URL to ~/.config/magi-cp/env
#   6) Run the smoke test to prove the gate fires
#
# Re-running is idempotent: re-pip-installs (upgrade), overwrites files in
# place. Persisted key is preserved unless you pass a new one explicitly.

set -euo pipefail

CLOUD_URL="${MAGI_CP_CLOUD_URL:-https://cloud.openmagi.ai}"
API_KEY="${1:-${MAGI_CP_API_KEY:-}}"

step() { printf "\033[1;34m→\033[0m %s\n" "$1"; }
warn() { printf "\033[1;33m!\033[0m %s\n" "$1" >&2; }
fail() { printf "\033[1;31m✗\033[0m %s\n" "$1" >&2; exit 1; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$1"; }

if [ -z "$API_KEY" ]; then
  fail "usage: install.sh mcp_…   (your alpha API key, sent to you by email)"
fi
case "$API_KEY" in
  mcp_*) ;;
  *) fail "API key must start with 'mcp_'. Got: ${API_KEY:0:8}…" ;;
esac

step "Detecting python3.11+"
PY=""
for cand in python3.13 python3.12 python3.11 python3; do
  if command -v "$cand" >/dev/null 2>&1; then
    if "$cand" -c 'import sys; sys.exit(0 if sys.version_info >= (3,11) else 1)' 2>/dev/null; then
      PY="$cand"; break
    fi
  fi
done
[ -n "$PY" ] || fail "python3.11+ not found. Install via 'brew install python@3.12' (macOS) or your distro package manager."
ok "using $PY ($("$PY" --version))"

step "Installing magi-cp Python package"
"$PY" -m pip install --user --upgrade \
  "magi-cp @ git+https://github.com/openmagi/magi-control-plane.git" \
  >/tmp/magi-cp-install.log 2>&1 \
  || fail "pip install failed — see /tmp/magi-cp-install.log"

# ~/.local/bin must be on PATH so `magi-cp-gate` is callable from managed-settings.
LBIN="$HOME/.local/bin"
mkdir -p "$LBIN"
case ":$PATH:" in
  *":$LBIN:"*) ;;
  *) warn "$LBIN is not on PATH — add 'export PATH=\$HOME/.local/bin:\$PATH' to your shell rc" ;;
esac
ok "magi-cp installed"

step "Downloading managed-settings.json + magi-gate.sh from $CLOUD_URL"
CLAUDE_DIR="$HOME/.claude"
mkdir -p "$CLAUDE_DIR"
curl -fsSL "$CLOUD_URL/api/downloads/managed-settings" \
  -o "$CLAUDE_DIR/managed-settings.json" \
  || fail "could not fetch managed-settings.json from $CLOUD_URL"
curl -fsSL "$CLOUD_URL/api/downloads/gate-binary" \
  -o "$LBIN/magi-gate.sh" \
  || fail "could not fetch magi-gate.sh from $CLOUD_URL"
chmod 0755 "$LBIN/magi-gate.sh"
ok "wrote $CLAUDE_DIR/managed-settings.json + $LBIN/magi-gate.sh"

# managed-settings.json embeds /usr/local/bin/magi-gate.sh as the default
# command path. Rewrite to the per-user path so we don't need sudo.
"$PY" - "$CLAUDE_DIR/managed-settings.json" "$LBIN/magi-gate.sh" <<'PY'
import json, sys
p = sys.argv[1]
data = json.load(open(p))
for hooks in data.get("hooks", {}).values():
    for block in hooks:
        for h in block.get("hooks", []):
            if h.get("type") == "command":
                h["command"] = sys.argv[2]
open(p, "w").write(json.dumps(data, indent=2, sort_keys=True) + "\n")
PY
ok "rewrote managed-settings to use $LBIN/magi-gate.sh"

step "Persisting key + cloud URL"
ENV_DIR="$HOME/.config/magi-cp"
mkdir -p "$ENV_DIR"
chmod 0700 "$ENV_DIR"
cat > "$ENV_DIR/env" <<EOF
# Auto-generated by magi-cp quickstart — do not edit unless you know what you're doing.
MAGI_CP_API_KEY=$API_KEY
MAGI_CP_CLOUD_URL=$CLOUD_URL
EOF
chmod 0600 "$ENV_DIR/env"
ok "saved $ENV_DIR/env (0600)"

# Source from common shell rcs (zsh + bash) if not already.
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [ -f "$rc" ] || continue
  if ! grep -q "magi-cp/env" "$rc" 2>/dev/null; then
    printf '\n# magi-cp\n[ -f "$HOME/.config/magi-cp/env" ] && set -a && . "$HOME/.config/magi-cp/env" && set +a\n' >> "$rc"
    ok "appended sourcing line to $rc"
  fi
done

step "Smoke test — confirming the gate fires correctly"
export MAGI_CP_API_KEY="$API_KEY"
export MAGI_CP_CLOUD_URL="$CLOUD_URL"
SMOKE_LOG=$(mktemp)
if bash "$(dirname "$0")/smoke-test.sh" >"$SMOKE_LOG" 2>&1; then
  ok "smoke test passed"
else
  warn "smoke test failed — log: $SMOKE_LOG"
  cat "$SMOKE_LOG" >&2
  exit 1
fi

cat <<EOF

\033[1;32m✓ Install complete.\033[0m

Next steps:
  1) Restart your shell  (or: source ~/.config/magi-cp/env)
  2) Restart Claude Code   (so it reads ~/.claude/managed-settings.json)
  3) Open your dashboard:   $CLOUD_URL/welcome

Verify install at any time:
  bash <(curl -fsSL $CLOUD_URL/install/smoke-test.sh)

EOF
